#ifndef NES_CPU_OPCODE_TABLE_H_
#define NES_CPU_OPCODE_TABLE_H_"

#define NUM_OPCODES 256"

namespace nes_cpu {
    struct OpcodeProperties {
        uint8_t (*op)(uint16_t);
        uint16_t (*addressing_mode)();
        uint8_t cycles;
        uint8_t penalty;  // penalty for crossing a page (cycles)
    };

    const OpcodeProperties opcodes[NUM_OPCODES] = {
        {.op=&BRK, .addressing_mode = &AMImplied, .cycles = 7, .cross_page_penalty = 0},
        {.op=&ORA, .addressing_mode = &AMIndexedIndirect, .cycles = 6, .cross_page_penalty = 0},
        {},
        {},
        {.op=&NOP, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&ORA, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&ASL, .addressing_mode = &AMZeroPage, .cycles = 5, .cross_page_penalty = 0},
        {},
        {.op=&PHP, .addressing_mode = &AMImplied, .cycles = 3, .cross_page_penalty = 0},
        {.op=&ORA, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&ASL, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&NOP, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&ORA, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&ASL, .addressing_mode = &AMAbsoulte, .cycles = 6, .cross_page_penalty = 0},
        {},
        {.op=&BPL, .addressing_mode = &AMRelative, .cycles = 2, .cross_page_penalty = 1},
        {.op=&ORA, .addressing_mode = &AMIndirectIndexed, .cycles = 5, .cross_page_penalty = 1},
        {},
        {},
        {.op=&NOP, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&ORA, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&ASL, .addressing_mode = &AMZeroPageX, .cycles = 6, .cross_page_penalty = 0},
        {},
        {.op=&CLC, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&ORA, .addressing_mode = &AMAbsoluteY, .cycles = 4, .cross_page_penalty = 1},
        {.op=&NOP, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&NOP, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&ORA, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&ASL, .addressing_mode = &AMAbsoluteX, .cycles = 7, .cross_page_penalty = 0},
        {},
        {.op=&JSR, .addressing_mode = &AMAbsoulte, .cycles = 6, .cross_page_penalty = 0},
        {.op=&AND, .addressing_mode = &AMIndexedIndirect, .cycles = 6, .cross_page_penalty = 0},
        {},
        {},
        {.op=&BIT, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&AND, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&ROL, .addressing_mode = &AMZeroPage, .cycles = 5, .cross_page_penalty = 0},
        {},
        {.op=&PLP, .addressing_mode = &AMImplied, .cycles = 4, .cross_page_penalty = 0},
        {.op=&AND, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&ROL, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&BIT, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&AND, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&ROL, .addressing_mode = &AMAbsoulte, .cycles = 6, .cross_page_penalty = 0},
        {},
        {.op=&BMI, .addressing_mode = &AMRelative, .cycles = 2, .cross_page_penalty = 1},
        {.op=&AND, .addressing_mode = &AMIndirectIndexed, .cycles = 5, .cross_page_penalty = 1},
        {},
        {},
        {.op=&NOP, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&AND, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&ROL, .addressing_mode = &AMZeroPageX, .cycles = 6, .cross_page_penalty = 0},
        {},
        {.op=&SEC, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&AND, .addressing_mode = &AMAbsoluteY, .cycles = 4, .cross_page_penalty = 1},
        {.op=&NOP, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&NOP, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&AND, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&ROL, .addressing_mode = &AMAbsoluteX, .cycles = 7, .cross_page_penalty = 0},
        {},
        {.op=&RTI, .addressing_mode = &AMImplied, .cycles = 6, .cross_page_penalty = 0},
        {.op=&EOR, .addressing_mode = &AMIndexedIndirect, .cycles = 6, .cross_page_penalty = 0},
        {},
        {},
        {.op=&NOP, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&EOR, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&LSR, .addressing_mode = &AMZeroPage, .cycles = 5, .cross_page_penalty = 0},
        {},
        {.op=&PHA, .addressing_mode = &AMImplied, .cycles = 3, .cross_page_penalty = 0},
        {.op=&EOR, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&LSR, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&JMP, .addressing_mode = &AMAbsoulte, .cycles = 3, .cross_page_penalty = 0},
        {.op=&EOR, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&LSR, .addressing_mode = &AMAbsoulte, .cycles = 6, .cross_page_penalty = 0},
        {},
        {.op=&BVC, .addressing_mode = &AMRelative, .cycles = 2, .cross_page_penalty = 1},
        {.op=&EOR, .addressing_mode = &AMIndirectIndexed, .cycles = 5, .cross_page_penalty = 1},
        {},
        {},
        {.op=&NOP, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&EOR, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&LSR, .addressing_mode = &AMZeroPageX, .cycles = 6, .cross_page_penalty = 0},
        {},
        {.op=&CLI, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&EOR, .addressing_mode = &AMAbsoluteY, .cycles = 4, .cross_page_penalty = 1},
        {.op=&NOP, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&NOP, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&EOR, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&LSR, .addressing_mode = &AMAbsoluteX, .cycles = 7, .cross_page_penalty = 0},
        {},
        {.op=&RTS, .addressing_mode = &AMImplied, .cycles = 6, .cross_page_penalty = 0},
        {.op=&ADC, .addressing_mode = &AMIndexedIndirect, .cycles = 6, .cross_page_penalty = 0},
        {},
        {},
        {.op=&NOP, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&ADC, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&ROR, .addressing_mode = &AMZeroPage, .cycles = 5, .cross_page_penalty = 0},
        {},
        {.op=&PLA, .addressing_mode = &AMImplied, .cycles = 4, .cross_page_penalty = 0},
        {.op=&ADC, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&ROR, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&JMP, .addressing_mode = &AMIndirect, .cycles = 5, .cross_page_penalty = 0},
        {.op=&ADC, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&ROR, .addressing_mode = &AMAbsoulte, .cycles = 6, .cross_page_penalty = 0},
        {},
        {.op=&BVS, .addressing_mode = &AMRelative, .cycles = 2, .cross_page_penalty = 1},
        {.op=&ADC, .addressing_mode = &AMIndirectIndexed, .cycles = 5, .cross_page_penalty = 1},
        {},
        {},
        {.op=&NOP, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&ADC, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&ROR, .addressing_mode = &AMZeroPageX, .cycles = 6, .cross_page_penalty = 0},
        {},
        {.op=&SEI, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&ADC, .addressing_mode = &AMAbsoluteY, .cycles = 4, .cross_page_penalty = 1},
        {.op=&NOP, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&NOP, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&ADC, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&ROR, .addressing_mode = &AMAbsoluteX, .cycles = 7, .cross_page_penalty = 0},
        {},
        {.op=&NOP, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&STA, .addressing_mode = &AMIndexedIndirect, .cycles = 6, .cross_page_penalty = 0},
        {.op=&NOP, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&STY, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&STA, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&STX, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {},
        {.op=&DEY, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&NOP, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&TXA, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&STY, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&STA, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&STX, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {},
        {.op=&BCC, .addressing_mode = &AMRelative, .cycles = 2, .cross_page_penalty = 1},
        {.op=&STA, .addressing_mode = &AMIndirectIndexed, .cycles = 6, .cross_page_penalty = 0},
        {},
        {},
        {.op=&STY, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&STA, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&STX, .addressing_mode = &AMZeroPageY, .cycles = 4, .cross_page_penalty = 0},
        {},
        {.op=&TYA, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&STA, .addressing_mode = &AMAbsoluteY, .cycles = 5, .cross_page_penalty = 0},
        {.op=&TXS, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {},
        {.op=&STA, .addressing_mode = &AMAbsoluteX, .cycles = 5, .cross_page_penalty = 0},
        {},
        {},
        {.op=&LDY, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&LDA, .addressing_mode = &AMIndexedIndirect, .cycles = 6, .cross_page_penalty = 0},
        {.op=&LDX, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&LDY, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&LDA, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&LDX, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {},
        {.op=&TAY, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&LDA, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&TAX, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&LDY, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&LDA, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&LDX, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {},
        {.op=&BCS, .addressing_mode = &AMRelative, .cycles = 2, .cross_page_penalty = 1},
        {.op=&LDA, .addressing_mode = &AMIndirectIndexed, .cycles = 5, .cross_page_penalty = 1},
        {},
        {},
        {.op=&LDY, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&LDA, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&LDX, .addressing_mode = &AMZeroPageY, .cycles = 4, .cross_page_penalty = 0},
        {},
        {.op=&CLV, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&LDA, .addressing_mode = &AMAbsoluteY, .cycles = 4, .cross_page_penalty = 1},
        {.op=&TSX, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&LDY, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&LDA, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&LDX, .addressing_mode = &AMAbsoluteY, .cycles = 4, .cross_page_penalty = 1},
        {},
        {.op=&CPY, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&CMP, .addressing_mode = &AMIndexedIndirect, .cycles = 6, .cross_page_penalty = 0},
        {.op=&NOP, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&CPY, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&CMP, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&DEC, .addressing_mode = &AMZeroPage, .cycles = 5, .cross_page_penalty = 0},
        {},
        {.op=&INY, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&CMP, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&DEX, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&CPY, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&CMP, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&DEC, .addressing_mode = &AMAbsoulte, .cycles = 6, .cross_page_penalty = 0},
        {},
        {.op=&BNE, .addressing_mode = &AMRelative, .cycles = 2, .cross_page_penalty = 1},
        {.op=&CMP, .addressing_mode = &AMIndirectIndexed, .cycles = 5, .cross_page_penalty = 1},
        {},
        {},
        {.op=&NOP, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&CMP, .addressing_mode = &AMZeroPageX, .cycles = 4, .cross_page_penalty = 0},
        {.op=&DEC, .addressing_mode = &AMZeroPageX, .cycles = 6, .cross_page_penalty = 0},
        {},
        {.op=&CLD, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&CMP, .addressing_mode = &AMAbsoluteY, .cycles = 4, .cross_page_penalty = 1},
        {.op=&NOP, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&NOP, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&CMP, .addressing_mode = &AMAbsoluteX, .cycles = 4, .cross_page_penalty = 1},
        {.op=&DEC, .addressing_mode = &AMAbsoluteX, .cycles = 7, .cross_page_penalty = 0},
        {},
        {.op=&CPX, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&SBC, .addressing_mode = &AMIndexedIndirect, .cycles = 6, .cross_page_penalty = 0},
        {.op=&NOP, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {},
        {.op=&CPX, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&SBC, .addressing_mode = &AMZeroPage, .cycles = 3, .cross_page_penalty = 0},
        {.op=&INC, .addressing_mode = &AMZeroPage, .cycles = 5, .cross_page_penalty = 0},
        {},
        {.op=&INX, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&SBC, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&NOP, .addressing_mode = &AMImplied, .cycles = 2, .cross_page_penalty = 0},
        {.op=&SBC, .addressing_mode = &AMImmediate, .cycles = 2, .cross_page_penalty = 0},
        {.op=&CPX, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&SBC, .addressing_mode = &AMAbsoulte, .cycles = 4, .cross_page_penalty = 0},
        {.op=&INC, .addressing_mode = &AMAbsoulte, .cycles = 6, .cross_page_penalty = 0},
        {}
    }
}
#endif  // NES_CPU_OPCODE_TABLE_H_

